services:
	mongodb:
	 image:mongo
	 container_name:mongo_db
	 ports:
	  - 27017:27017
	 volumes:
	  - mongo:/data
	 environment:
	  - MONGO_INITDB_ROOT_USERNAME=admin
	  - MONGO_INITDB_ROOT_PASSWORD=louay
	mongo-express:
	 image:mongo-express
	 container_name:mongo_express
	 ports:
	  - 8081:8081
	 environment:
	  - ME_CONFIG_MONGODB_ADMINUSERNAME:admin
	  - ME_CONFIG_MONGODB_ADMINPASSWORD:louay
	  - ME_CONFIG_MONGODB_SERVER:mongodb
volumes:
 mongo:{}